# Generated by Django 5.1.5 on 2025-02-07 14:36

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.doctor_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_directory_path),
        ),
    ]
