# Generated by Django 5.1.5 on 2025-02-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserItems',
        ),
    ]
