# Generated by Django 5.1.5 on 2025-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('chat', 'Chat')], default='chat', max_length=10),
        ),
    ]
