# Generated by Django 5.1.5 on 2025-02-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrealtime', '0001_initial'),
        ('consultation', '0003_alter_consultation_options_consultation_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatrealtime',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatrealtime',
            name='consultation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='consultation.consultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatrealtime',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
