# Generated by Django 5.1.5 on 2025-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revoshop', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_option',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='active', max_length=20),
        ),
    ]
