# Generated by Django 5.1.5 on 2025-02-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.TextField()),
                ('regency_name', models.CharField(max_length=250)),
                ('district_name', models.CharField(max_length=250)),
                ('village_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('person_responsible', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('verification', 'Verification'), ('available', 'Available')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('image_proof', models.TextField()),
                ('qty', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('accepted_by', models.CharField(default='ai', max_length=250)),
                ('accepted_coin', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('warning', 'Warning'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.trash')),
            ],
        ),
    ]
