# Generated by Django 5.1.5 on 2025-02-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.PositiveIntegerField()),
                ('totals_swap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('warning', 'Warning'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentoption')),
            ],
        ),
    ]
