# Generated by Django 5.1.5 on 2025-02-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwapRecord',
        ),
    ]
